import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { SharedModule } from './shared.module';
import { TranslateModule } from '@ngx-translate/core';
import { FlexLayoutModule } from '@angular/flex-layout';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

// import { GlobalService } from './services/global.service';

import { SidebarComponent, TopnavComponent, NavComponent, PageHeaderComponent, SnackBarComponent ,ActionNotificationComponent, AlertComponent, DeleteEntityDialogComponent, FetchEntityDialogComponent, UpdateStatusDialogComponent, AlertEntityDialogComponent, AlertActionEntityDialogComponent, LoadingScreenComponent, ModalViewDialogComponent, EnumViewComponent, ErrorEntityDialogComponent, ConfirmEntityDialogComponent, ModalIframeDialogComponent, WidgetComponent} from './components';
import { CkeditorBlockComponent, WidgetDummyComponent, TextBlockComponent, VideoBlockComponent, PictureBlockComponent, DisqusBlockComponent, SocialFeedBlockComponent, CalendarBlockComponent, ShareBlockComponent, PatientsBlockComponent, InquiryBlockComponent, SurveyBlockComponent, QuestionnaireBlockComponent, QuestionnaireSubOptionComponent, DescriptionSubOptionComponent, StartWrapperBlockComponent, AddSpaceComponent, FormTitleBlockComponent, QuestionsBlockComponent, AttendanceBlockComponent, ConfirmationBlockComponent, PasswordBlockComponent, NextBlockComponent, FormPhotoComponent, FormDocumentComponent, PainLevelComponent, DrawToolBlockComponent, PhysicianBlockComponent, EndWrapperBlockComponent, FillBlockComponent, NotesBlockComponent, ButtonsBlockComponent, ContactUsBlockComponent, PlacefullBlockComponent, AddToCartBlockComponent, CartBlockComponent, BlanksFormBlockComponent, ExclusiveUrlBlockComponent, FileUploadBlockComponent, PushpayBlockComponent, ThreedCartBlockComponent, BlogsBlockComponent, ChatBlockComponent,  AccountBlockComponent, ProfileBlockComponent, ModalGalleryDialogComponent } from './components';
import { ModalTilesDialogComponent, ModalDialDialogComponent, ModalEmailDialogComponent, ModalVideoDialogComponent, ModalPagesDialogComponent, ModalTileCloseDialogComponent, ModalEventMediaDialogComponent, ModalFormMediaDialogComponent, ModalEventDocumentDialogComponent, ModalCalenderDialogComponent, ModalPreviewDialogComponent, ModalBackgroundDialogComponent, ModalVideosDialogComponent, CustomSelectAutocompleteComponent } from './components';


import { Utils } from './helpers/utils';
import { CKEditorModule } from 'ngx-ckeditor';
import { ImageCropperModule } from 'ngx-image-cropper';

@NgModule({
    imports: [
        CommonModule,
        RouterModule,
        SharedModule,
        TranslateModule,
        FormsModule,
        ReactiveFormsModule,
        CKEditorModule,
        ImageCropperModule,
        FlexLayoutModule.withConfig({addFlexToParent: false})
    ],
    providers: [
        // GlobalService
        Utils
    ],
    entryComponents: [
        SnackBarComponent,
        DeleteEntityDialogComponent,
        ErrorEntityDialogComponent,
        ConfirmEntityDialogComponent,
        ModalIframeDialogComponent,
        FetchEntityDialogComponent,
        UpdateStatusDialogComponent,
        AlertEntityDialogComponent,
        AlertActionEntityDialogComponent,
        LoadingScreenComponent,
        ModalViewDialogComponent,
        EnumViewComponent,
        WidgetComponent,
        WidgetDummyComponent,
        VideoBlockComponent,
        PictureBlockComponent,
        DisqusBlockComponent,
        SocialFeedBlockComponent,
        CalendarBlockComponent,
        ShareBlockComponent,
        PatientsBlockComponent,
        InquiryBlockComponent,
        SurveyBlockComponent,
        QuestionnaireBlockComponent,
        QuestionnaireSubOptionComponent,
        DescriptionSubOptionComponent,
        StartWrapperBlockComponent,
        AddSpaceComponent,
        FormTitleBlockComponent,
        QuestionsBlockComponent,
        AttendanceBlockComponent,
        ConfirmationBlockComponent,
        PasswordBlockComponent,
        NextBlockComponent,
        FormPhotoComponent,
        FormDocumentComponent,
        PainLevelComponent,
        DrawToolBlockComponent,
        PhysicianBlockComponent,
        EndWrapperBlockComponent,
        FillBlockComponent,
        NotesBlockComponent,
        ButtonsBlockComponent,
        ContactUsBlockComponent,
        PlacefullBlockComponent,
        AddToCartBlockComponent,
        CartBlockComponent,
        BlanksFormBlockComponent,
        ExclusiveUrlBlockComponent,
        FileUploadBlockComponent,
        PushpayBlockComponent,
        ThreedCartBlockComponent,
        BlogsBlockComponent,
        ChatBlockComponent,
        AccountBlockComponent,
        ProfileBlockComponent,
        TextBlockComponent,
        CkeditorBlockComponent,
        ModalGalleryDialogComponent,
        ModalTilesDialogComponent,
        ModalDialDialogComponent,
        ModalEmailDialogComponent,
        ModalVideoDialogComponent,
        ModalVideosDialogComponent,
        ModalPagesDialogComponent,
        ModalTileCloseDialogComponent,
        ModalEventMediaDialogComponent,
        ModalFormMediaDialogComponent,
        ModalEventDocumentDialogComponent,
        ModalCalenderDialogComponent,
        ModalPreviewDialogComponent,
        ModalBackgroundDialogComponent,
        CustomSelectAutocompleteComponent
    ],
    declarations: [
        SidebarComponent,
        TopnavComponent,
        NavComponent,
        PageHeaderComponent,
        SnackBarComponent,
        EnumViewComponent,
        ActionNotificationComponent,
        ModalViewDialogComponent,
        AlertComponent,
        DeleteEntityDialogComponent,
        ErrorEntityDialogComponent,
        ConfirmEntityDialogComponent,
        ModalIframeDialogComponent,
        FetchEntityDialogComponent,
        UpdateStatusDialogComponent,
        AlertEntityDialogComponent,
        AlertActionEntityDialogComponent,
        LoadingScreenComponent,
        WidgetComponent,
        WidgetDummyComponent,
        VideoBlockComponent,
        PictureBlockComponent,
        DisqusBlockComponent,
        SocialFeedBlockComponent,
        CalendarBlockComponent,
        ShareBlockComponent,
        PatientsBlockComponent,
        InquiryBlockComponent,
        SurveyBlockComponent,
        QuestionnaireBlockComponent,
        QuestionnaireSubOptionComponent,
        DescriptionSubOptionComponent,
        StartWrapperBlockComponent,
        AddSpaceComponent,
        FormTitleBlockComponent,
        QuestionsBlockComponent,
        AttendanceBlockComponent,
        ConfirmationBlockComponent,
        PasswordBlockComponent,
        NextBlockComponent,
        FormPhotoComponent,
        FormDocumentComponent,
        PainLevelComponent,
        DrawToolBlockComponent,
        PhysicianBlockComponent,
        EndWrapperBlockComponent,
        FillBlockComponent,
        NotesBlockComponent,
        ButtonsBlockComponent,
        ContactUsBlockComponent,
        PlacefullBlockComponent,
        AddToCartBlockComponent,
        CartBlockComponent,
        BlanksFormBlockComponent,
        ExclusiveUrlBlockComponent,
        FileUploadBlockComponent,
        PushpayBlockComponent,
        ThreedCartBlockComponent,
        BlogsBlockComponent,
        ChatBlockComponent,
        AccountBlockComponent,
        ProfileBlockComponent,
        TextBlockComponent,
        CkeditorBlockComponent,
        ModalGalleryDialogComponent,
        ModalTilesDialogComponent,
        ModalDialDialogComponent,
        ModalEmailDialogComponent,
        ModalVideoDialogComponent,
        ModalVideosDialogComponent,
        ModalPagesDialogComponent,
        ModalTileCloseDialogComponent,
        ModalEventMediaDialogComponent,
        ModalFormMediaDialogComponent,
        ModalEventDocumentDialogComponent,
        ModalCalenderDialogComponent,
        ModalPreviewDialogComponent,
        ModalBackgroundDialogComponent,
        CustomSelectAutocompleteComponent
    ],
    exports: [
        SidebarComponent,
        TopnavComponent,
        NavComponent,
        PageHeaderComponent,
        ActionNotificationComponent,
        ModalViewDialogComponent,
        AlertComponent,
        DeleteEntityDialogComponent,
        ErrorEntityDialogComponent,
        ConfirmEntityDialogComponent,
        ModalIframeDialogComponent,
        FetchEntityDialogComponent,
        UpdateStatusDialogComponent,
        AlertEntityDialogComponent,
        AlertActionEntityDialogComponent,
        EnumViewComponent,
        LoadingScreenComponent,
        WidgetComponent,
        WidgetDummyComponent,
        VideoBlockComponent,
        PictureBlockComponent,
        DisqusBlockComponent,
        SocialFeedBlockComponent,
        CalendarBlockComponent,
        ShareBlockComponent,
        PatientsBlockComponent,
        InquiryBlockComponent,
        SurveyBlockComponent,
        QuestionnaireBlockComponent,
        QuestionnaireSubOptionComponent,
        DescriptionSubOptionComponent,
        StartWrapperBlockComponent,
        AddSpaceComponent,
        FormTitleBlockComponent,
        QuestionsBlockComponent,
        AttendanceBlockComponent,
        ConfirmationBlockComponent,
        PasswordBlockComponent,
        NextBlockComponent,
        FormPhotoComponent,
        FormDocumentComponent,
        PainLevelComponent,
        DrawToolBlockComponent,
        PhysicianBlockComponent,
        EndWrapperBlockComponent,
        FillBlockComponent,
        NotesBlockComponent,
        ButtonsBlockComponent,
        ContactUsBlockComponent,
        PlacefullBlockComponent,
        AddToCartBlockComponent,
        CartBlockComponent,
        BlanksFormBlockComponent,
        ExclusiveUrlBlockComponent,
        FileUploadBlockComponent,
        PushpayBlockComponent,
        ThreedCartBlockComponent,
        BlogsBlockComponent,
        ChatBlockComponent,
        AccountBlockComponent,
        ProfileBlockComponent,
        TextBlockComponent,
        CkeditorBlockComponent,
        ModalGalleryDialogComponent,
        ModalTilesDialogComponent,
        ModalDialDialogComponent,
        ModalEmailDialogComponent,
        ModalVideoDialogComponent,
        ModalVideosDialogComponent,
        ModalPagesDialogComponent,
        ModalTileCloseDialogComponent,
        ModalEventMediaDialogComponent,
        ModalFormMediaDialogComponent,
        ModalEventDocumentDialogComponent,
        ModalCalenderDialogComponent,
        ModalPreviewDialogComponent,
        ModalBackgroundDialogComponent,
        CustomSelectAutocompleteComponent
    ]
})
export class LayoutComponentModule { }
